[metadata]
version = "1.0"

[versions]
adventure = "4.10.1"
adventurePlatform = "4.1.0"
checkstyle = "10.2"
examination = "1.3.0"
fabricApi = "0.51.1+1.18.2"
indra = "2.1.1"
parchment = "1.18.1:2021.12.19"
quiltflower = "1.8.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-key = { module = "net.kyori:adventure-key", version.ref = "adventure" }
adventure-platform-api = { module = "net.kyori:adventure-platform-api", version.ref = "adventurePlatform" }
adventure-textSerializerPlain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
adventure-textSerializerGson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-textMinimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
colonel = "ca.stellardrift:colonel:0.2.2"
examination-api = { module = "net.kyori:examination-api", version.ref = "examination" }
examination-string = { module = "net.kyori:examination-string", version.ref = "examination" }
fabric-loader = "net.fabricmc:fabric-loader:0.14.0"
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
jetbrainsAnnotations = "org.jetbrains:annotations:23.0.0"
minecraft = "com.mojang:minecraft:1.18.2"

# build
stylecheck = "ca.stellardrift:stylecheck:0.1"
contractValidator = "ca.stellardrift:contract-validator:1.0.1"

# For Renovate, do not use directly
zQuiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }
zCheckstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

[plugins]
loom = "fabric-loom:0.11.+"
loomQuiltflower = "io.github.juuxel.loom-quiltflower:1.7.1"
configurateTransformations = "ca.stellardrift.configurate-transformations:5.0.1"
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-licenseHeader = { id = "net.kyori.indra.license-header", version.ref = "indra" }
indra-checkstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
