[metadata]
version = "1.0"

[versions]
adventure = "4.12.0"
adventurePlatform = "4.1.2"
autoService = "1.0.1"
checkstyle = "10.5.0"
examination = "1.3.0"
fabricApi = "0.67.1+1.19.2"
fabricLoader = "0.14.10"
indra = "3.0.1"
minecraft = "1.19.2"
parchment = "1.19.2:2022.11.27"
quiltflower = "1.9.0"
spotless = "6.12.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-key = { module = "net.kyori:adventure-key", version.ref = "adventure" }
adventure-platform-api = { module = "net.kyori:adventure-platform-api", version.ref = "adventurePlatform" }
adventure-textLoggerSlf4j = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
adventure-textMinimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-textSerializerPlain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
adventure-textSerializerGson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }

examination-api = { module = "net.kyori:examination-api", version.ref = "examination" }
examination-string = { module = "net.kyori:examination-string", version.ref = "examination" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader"}
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
jetbrainsAnnotations = "org.jetbrains:annotations:23.0.0"
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# build
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
contractValidator = "ca.stellardrift:contract-validator:1.0.1"
stylecheck = "ca.stellardrift:stylecheck:0.2.0"

# For Renovate, do not use directly
zCheckstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
zQuiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }

[plugins]
configurateTransformations = "ca.stellardrift.configurate-transformations:6.0.1"
eclipseApt = "com.diffplug.eclipse.apt:3.40.0"
loom = "fabric-loom:1.0.+"
loomQuiltflower = "io.github.juuxel.loom-quiltflower:1.8.0"
ideaExt = "org.jetbrains.gradle.plugin.idea-ext:1.1.6"
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-licenseHeader = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
indra-checkstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
